### PR TITLE
refactor: use babel@^7.0.0

### PR DESCRIPTION
**Pull request by czycha**
Refactored to use Babel 7. The duplicate `babel-core` is because `babel-jest` requires this for some reason.

### CODE REVIEW

**Comment by FezVrasta** [comment]
I think there's a special version of babel-core to use with Jest. 

They say to do this:

```
yarn add --dev babel-jest @babel/core babel-core@7.0.0-bridge.0
```

May you update the PR please?

**Comment by czycha** [comment]
Upgraded.

**Comment by FezVrasta** [comment]
Thanks, I'll test it as soon my ISP decides to give me back my internet connection...

**Comment by piecyk** [comment]
👏

**Comment by piecyk** [comment]
@FezVrasta Don't like to ask but could you also releases the babel stuff? 😉Current for me react-popper is pulling also babel6 into bundle so as at the outcome got babel6 and 7

**Comment by FezVrasta** [comment]
of course, 1.3.2 published

**Comment by piecyk** [comment]
thanks 🙌

**Pull request merged**
