### PR TITLE
fixes TS error message thrown when importing popper

### PR DESCRIPTION
**Pull request by Ricka7x**
there was an error on line 24

### CODE REVIEW

**Comment by Ricka7x** [comment]
it looks like there was a typo on line 24 on react-popper.d.ts causing this error to pop up ERROR in [at-loader] ./node_modules/react-popper/typings/react-popper.d.ts:24:16
    TS8020: JSDoc types can only be used inside documentation comments.

**Comment by FezVrasta** [comment]
Thanks. Do you know why the tests don't throw this error?

**Comment by FezVrasta** [comment]
@Ricka7x any updates on my question maybe?

**Comment by Ricka7x** [comment]
@FezVrasta I don't see you're testing for types anywhere. a linter would be a good Idea though

**Comment by FezVrasta** [comment]
You can run `yarn test:ts`

**Comment by FezVrasta** [comment]
I'm going to close this for unresponsiveness from the OP. If anyone can explain make the TS tests fail I'll gladly accept a PR of this kind.

**Pull request closed without merging**
