### PR TITLE
build: remove @types/react from dependencies

### LINKED ISSUE #239: remove @types/react from dependencies
From #234, I think library shouldn't include types of other dependencies. If types has to be in dependencies, it has to be in react project itself, so other dependencies those depend on it, don't have to make the redundancy.

I have tons of examples
react-dropzone: https://github.com/react-dropzone/react-dropzone/blob/master/package.json
react-datepicker: https://github.com/Hacker0x01/react-datepicker/blob/master/package.json
reactstrap: https://github.com/reactstrap/reactstrap/blob/master/package.json

But if it's `@type/react-popper`, then yeah, it'd make a bit sense.

### PR DESCRIPTION
**Pull request by pd4d10**
fix #239

### CODE REVIEW

**Comment by mykas** [comment]
Can we merge this? we have issues with this too.

**Comment by mykas** [comment]
Or at least put it in devDependencies.

**Comment by piecyk** [comment]
@FezVrasta This is correct solution, more at https://github.com/Microsoft/TypeScript/issues/9731#issuecomment-232864820 
Let's merge this ?

**Comment by FezVrasta** [comment]
I'm quite sure this will break something else, but let's do that...

**Comment by piecyk** [comment]
Eee, have more fait 🤗

**Pull request merged**
